### ISSUE TITLE
Docker compose Feature Request

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/aerial_wildlife_detection#13]
Hi, really interested in this project. One feature request is addition of a docker compose so we can get this up and running very quickly. Happy to assist if of interest.
Cheers
Robin

**Comment by bkellenb** [comment]
Hello Robin,

Thank you for the recommendation. I wanted to provide Docker containers for a long time but have been unable to do so due to time restrictions.
I am currently working on the [next big release](https://github.com/microsoft/aerial_wildlife_detection/tree/multiProject) of AIDE, but would be very glad indeed for assistance!

**Comment by bkellenb** [comment]
Hello Robin,

Thanks to the great work of contributor Jarek, AIDE now has support for Docker and Docker Compose!
See the new [branch](https://github.com/microsoft/aerial_wildlife_detection/tree/multiProject) of AIDE v2 for details.
It's not 100% tested and customizable yet, but we will be working on it.
