### ISSUE TITLE
Images can't be viewed after uploading

### ISSUE THREAD

**Issue by YangZhang-mizzou** [microsoft/aerial_wildlife_detection#27]
Hello All:

I have some problems when I try to view and label the images I uploaded.
Anyone have some suggestions for this? Thank you!
![Screenshot from 2021-01-21 13-37-26](https://user-images.githubusercontent.com/47132186/105403046-d5f65700-5bed-11eb-87e6-91732e1a0a92.png)

**Comment by YangZhang-mizzou** [comment]
I uploaded jpg images, size is 512 * 512.

**Comment by bkellenb** [comment]
Hello!

Sometimes this happens because the Web frontend tries to prematurely request the images from the FileServer. However, they should still get uploaded.
Can you conﬁrm whether they appear in the image browser when you click the "Data management" tab?

If not, I will try to replicate the scenario to ﬁnd the culprit. For this I'd need to know the following:
1. Are you running AIDE through Docker?
2. Are all services located on one machine, or is the FileServer being handled by another one?

**Comment by YangZhang-mizzou** [comment]
> Hello!
> 
> Sometimes this happens because the Web frontend tries to prematurely request the images from the FileServer. However, they should still get uploaded.
> Can you conﬁrm whether they appear in the image browser when you click the "Data management" tab?
> 
> If not, I will try to replicate the scenario to ﬁnd the culprit. For this I'd need to know the following:
> 
> 1. Are you running AIDE through Docker?
> 2. Are all services located on one machine, or is the FileServer being handled by another one?

Thank you for your reply! Yes they are in data management but still can not be viewed. For your questions:1.Yes, I run gpu mode through docker 2. yes, all process on one same machine.

**Comment by bkellenb** [comment]
Oh, my bad. I remember this bug and actually ﬁxed it in the [latest branch](https://github.com/microsoft/aerial_wildlife_detection/tree/aide_detectron2) I had been working on. This will soon be the new master, with plenty new features and other bugs resolved.

However, I just also ﬁxed the bug on the current master branch; if you pull the latest changes and reload the page the images should display ﬁne.

**Comment by YangZhang-mizzou** [comment]
> Oh, my bad. I remember this bug and had actually ﬁxed it a while ago in the [latest branch](https://github.com/microsoft/aerial_wildlife_detection/tree/aide_detectron2). This will soon be the new master, with plenty new features and other bugs resolved.
> 
> However, I just also resolved that issue in the current master branch; if you pull the latest changes and reload the page the images should display ﬁne. Can you conﬁrm?

Yes! Thank you for your help!

**Comment by bkellenb** [comment]
Thanks a lot! I'm closing this for now then.

**Comment by YangZhang-mizzou** [comment]
> Thanks a lot! I'm closing this for now then.

I am sorry but this problem has not been solved. After I pull your update I still can not view my images, when I click the hyperlink to images in server, I got the page like that showing this image does not exist. Same error still occur when I try it in aide-detectron2. 
![Screenshot from 2021-01-21 15-24-59](https://user-images.githubusercontent.com/47132186/105414719-73a55280-5bfd-11eb-8a2c-ee190c2de21f.png)
Do you have some comments? Thank you!

**Comment by YangZhang-mizzou** [comment]
Here is my setting.ini file. I only change values in [project]. should I do more?
[settings.txt](https://github.com/microsoft/aerial_wildlife_detection/files/5852516/settings.txt)

**Comment by bkellenb** [comment]
Hello,

You are absolutely right! The `docker/settings.ini` file contained an outdated default value for parameter `[Server] dataServer_uri`.
Thank you very much for pointing this out!

If your FileServer is running on the same machine as your web frontend, then this parameter should be left **empty** (or with a forward slash `/`). Only if your FileServer is running on an external machine should it be filled in (then with that machine's base URL).
This explains why `/files/` appeared twice in the suggested URL (as per your screenshot).

I have now ﬁxed this default value and also resolved other issues I found due to missing DB schema updates. Please pull the latest changes (both `master` and `aide_detectron2` branches have been updated) and verify the entries in the `settings.ini` ﬁle.

**Comment by YangZhang-mizzou** [comment]
> Hello,
> 
> You are absolutely right with the settings ﬁle! The `docker/settings.ini` file contained an outdated default value for parameter `dataServer_uri`.
> Thank you very much for pointing this out!
> 
> If your FileServer is running on the same machine as your web frontend, then this parameter should be left **empty** (or with a forward slash `/`). Only if your FileServer is running on an external machine should it be filled in (then with that machine's base URL).
> This explains why `/files/` appeared twice in the suggested URL (as per your screenshot).
> So, if you are running all services on one machine, your `settings.ini` ﬁle should have the following entry:
> 
> ```
> [Server]
> dataServer_uri =
> ```
> 
> I have now ﬁxed this default value and also resolved other issues I found due to missing DB schema updates. **Please pull the latest changes** (both `master` and `aide_detectron2` branches have been updated) and verify the entries in the `settings.ini` ﬁle.

Yes, it worked now. Thank you for your help!
