### ISSUE TITLE
Problem uploading images

### ISSUE THREAD

**Issue by ctorney** [microsoft/aerial_wildlife_detection#42]
Hi Beni,
should this line be including window.baseURL?

https://github.com/microsoft/aerial_wildlife_detection/blob/de150d03e267676876554f62188689cf4196f4bb/modules/ProjectAdministration/static/templates/panels/dataUpload.html#L165

I get an error when the baseURL is included but seems to work without it
Cheers

**Comment by bkellenb** [comment]
Hello Colin,

This error occurred due to a missing baseURL deﬁnition in the project setup wizard. I had this ﬁxed a long time ago in the [latest development branch](https://github.com/microsoft/aerial_wildlife_detection/commits/aide_detectron2), but forgot to apply it to the current master. This is now done (commit [#c864e47](https://github.com/microsoft/aerial_wildlife_detection/commit/c864e479b4ebe1f780deb9c87e0d303a8efa327c).

FYI: I will also soon replace the current master with the branch linked above—this will ofﬁcially introduce AIDE version 2.0, which comes with a plethora of new models, greatly spiced up Model Marketplace and hundreds of bug ﬁxes, too. Stay tuned!

**Comment by ctorney** [comment]
Thanks - I'll keep an eye out for the new release!
